### ISSUE TITLE
need to open file in https

### ISSUE THREAD

**Issue by vahidalvandi** [aminvakil/docker-alpine-ftp-server-tls#37]
hi
how i can open file in url with https?

**Comment by aminvakil** [comment]
Cannot be done, you need a webserver for that. This is a ftp server which uses tls by default.

**Comment by vahidalvandi** [comment]
> Cannot be done, you need a webserver for that. This is a ftp server which uses tls by default.

i want install ngnix , please help how port number need to proxed ? 21

**Comment by aminvakil** [comment]
You should read and understand basic principles of what you're talking about, nginx is used to reverse proxy http requests, this repository is a ftp server which obviously uses ftp protocol, you cannot reverse proxy ftp protocol using http reverse proxies.

You need something that proxies tcp protocol or something else, anyway unrelated to this repository.

And if this is getting exposed to the internet, do yourself and others a favour and let someone with experience handle it.
