### ISSUE TITLE
feat: support multiple architectures

### ISSUE THREAD

**Issue by fty4** [aminvakil/docker-alpine-ftp-server-tls#43]
Hello,

I would love to see more available architectures for this image (e.g. `linux/arm64`).
Currently there seems to be only [`amd64`](https://quay.io/repository/aminvakil/alpine-ftp-server-tls/manifest/sha256:3a582efd756f5d13674a6544dee46d711673cee85bf31ad8c97457f8a50e1578) available.

**Comment by aminvakil** [comment]
I currently don't have time to implement this, but I'd love to review a PR if someone does that.
